apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: api-secret-store
spec:
  provider:
    gcpsm:
      projectID: "develop-464014"
      auth:
        workloadIdentity:
          clusterLocation: "us-central1"
          clusterName: "argo-dev-0"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
.