apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: api-secret-store
spec:
  provider:
    gcpsm:
      projectID: "argo-prod-471308"
      auth:
        workloadIdentity:
          clusterLocation: "us-east1"
          clusterName: "argo-prd-0"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
