apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret-ext
  namespace: api
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: api-secret-store
  target:
    name: db-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: db-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-secret-ext-2
  namespace: api
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: api-secret-store
  target:
    name: telegram-secret
    creationPolicy: Owner
    template:
      type: stringData
      data:
        token: "{{ .token }}"
        chat_id: "{{ .chat_id }}"
  data:
    - secretKey: token
      remoteRef:
        key: telegram
        property: token
    - secretKey: chat_id
      remoteRef:
        key: telegram
        property: chat_id
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: api
spec:
  refreshInterval: 15h
  secretStoreRef:
    kind: ClusterSecretStore
    name: api-secret-store
  target:
    name: catalogo-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: db-credentials
